export const jobTitlesData: string[] = [
  "Frontend Developer",
  "Front-End Developer",
  "Frontend Engineer",
  "Front-End Engineer",
  "Senior Frontend Engineer",
  "Senior Front-End Engineer",
  "Senior Frontend Developer",
  "Senior Front-End Developer",
  "UI Developer",
  "UI Engineer",
  "React Developer",
  "React Engineer",
  "Next.js Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Web Developer",
  "Software Engineer",
  "Software Developer",
  "Application Developer",
  "Full Stack Developer",
  "Full-Stack Developer",
  "Full Stack Engineer",
  "Full-Stack Engineer",
  "Frontend Platform Engineer",
  "Frontend Architect",
  "Senior Software Engineer",
];
